### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
do_eval: true
finetuning_type: lora
lora_target: all    ####maybe we can change it to only attention
# lora_target: q_proj,v_proj
# lora_target: layers.28.self_attn.q_proj,layers.28.self_attn.v_proj  #### test specific layers
lora_rank: 8
lora_alpha: 16
lora_dropout: 0.05


### train dataset
dataset_dir: ./data
dataset: factscore_automized_claim_train
### eval dataset
eval_dataset: factscore_automized_claim_valid
template: llama3
cutoff_len: 1024
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/lora/factscore_automized_claim_classifer_sft_target_all
logging_steps: 10
### save strategy
save_strategy: steps
save_steps: 20
# save_strategy: epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
### eval 
per_device_eval_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval strategy
eval_strategy: steps
eval_steps: 20
# eval_strategy: epoch
load_best_model_at_end: true
