### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
do_eval: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z1_config.json

### train dataset
dataset_dir: ./data
dataset: automized_claim_train
### eval dataset
eval_dataset: automized_claim_valid
template: llama3
cutoff_len: 1024
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/fullmodel/automized_claim_classifer_sft
logging_steps: 10
### save strategy
save_strategy: steps
save_steps: 50
# save_strategy: epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
### eval 
per_device_eval_batch_size: 8
gradient_accumulation_steps: 1
# learning_rate: 1.0e-5
learning_rate: 2.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval strategy
eval_strategy: steps
eval_steps: 50
# eval_strategy: epoch
load_best_model_at_end: true

### only save model for full-model fine-tuning. Note: DeepSpeed can't be used with `save_only_model` along with `load_best_model_at_end`.
# save_only_model: true